project:
  type: book
number-depth: 2
toc-depth: 3
book:
  title: "Bio & Business Data Science"
  author: "Nicolas Meseth"
  sharing: [twitter, facebook, linkedin]
  toc-depth: 1
  chapters:
    - index.qmd
    #- part: case-binary-adding-machine.qmd
    #  chapters:
    #    - logic-gates.qmd
    - part: case-covid.qmd
      chapters: 
        - tidyverse.qmd
        - csv-format.qmd
        - trends.qmd
        - origin-of-data.qmd
    - part: case-twitter-a.qmd
      chapters: 
        - json-with-r.qmd
        - associations.qmd
        #- sql-intro.qmd
    - part: case-rewe.qmd
      chapters: 
        - proportions.qmd
    - part: case-limonade.qmd
      chapters:
        - long-wide-data.qmd
    - outliers.qmd
    - search_text.qmd
    - sample-bias.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  cache: true

