project:
  type: book
number-depth: 2
toc-depth: 2
book:
  title: "Bio & Business Data Science"
  author: "Nicolas Meseth"
  sharing: [twitter, facebook, linkedin]
  toc-depth: 1
  chapters:
    - index.qmd
    #- part: case-binary-adding-machine.qmd
    #  chapters:
    #    - logic-gates.qmd
    - part: case-covid.qmd
      chapters: 
        - tidyverse.qmd
        - r-load-csv-data.qmd
        - trends.qmd
    - part: case-twitter-a.qmd
      chapters: 
        - sql-intro.qmd
    - part: case-rewe.qmd
      chapters: 
        - proportions.qmd
    - part: case-limonade.qmd
      chapters:
        - long-wide-data.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    documentclass: scrreprt

editor: visual

