project:
  type: book
  resources: 
    - "data/"
number-depth: 2
toc-depth: 3
book:
  title: "Bio & Business Data Science"
  lang: de
  author: "Nicolas Meseth"
  sharing: [twitter, facebook, linkedin]
  toc-depth: 1
  chapters:
    - index.qmd
    
    - part: case-campusbier.qmd
      chapters: 
        - read-csv-files.qmd
        - explore-new-data-sets.qmd
    
    - part: case-climate-data.qmd
      chapters:
        - read-txt-files.qmd
        - tidyverse.qmd
        - select-columns.qmd
        
    #- part: case-shopify-sales.qmd
    #  chapters: 
    #   - read-rest-apis.qmd
    
    - part: case-covid.qmd
      chapters: 
        
        - csv-format.qmd
        - trends.qmd
        - origin-of-data.qmd
    - part: case-twitter-a.qmd
      chapters: 
        - json-with-r.qmd
        - associations.qmd
        #- sql-intro.qmd
    - part: case-rewe.qmd
      chapters: 
        - proportions.qmd
    - part: case-limonade.qmd
      chapters:
        - long-wide-data.qmd
    - part: case-open-food-facts.qmd
      chapters:
        - outliers.qmd
        - search_text.qmd
        - sample-bias.qmd
    - references.qmd

language:
    toc-title-document: "Inhalt"
    search-matching-documents-text: "Suchtreffer"

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    df-print: tibble
  pdf:
    documentclass: scrreprt
    

editor: source

execute:
  cache: false

