# CSV-Daten laden mit R

Im ersten Schritt jeder Datenanalyse müssen wir unserem Computer den Datensatz zur Verfügung stellen. Wir sprechen dabei auch vom *Laden* des Datesatzes. Dabei sagen wir dem Computer, wo die Daten zu finden sind und dass er sie für den schnelleren Zugriff in seinen Arbeitsspeicher holen soll. 

Daten liegen in den meisten Fällen in Form von Dateien vor. In manchen Fällen sind sie auch in einer Datenbank gespeichert. Im Fall einer Datei kann ein Datensatz innerhalb einer Datei in unterschiedlichen *Formaten* gespeichert werden. Ein gängiges Format ist das CSV-Format.

## Das CSV-Format

CSV steht für *Comma Separated Values* und es beschreibt ein Format, um *strukturierte Daten* in einer Textdatei abzuspeichern. Ihr erkennt eine Textdatei im CSV-Format an der Endung `.csv`.

Das CSV-Format ist das am weitesten verbreitete Format für den Austausch von strukturierten Daten. Fast jede Software, die Daten verwaltet oder analysiert, bietet Schnittstellen für CSV-Dateien an. Es gibt gute Gründe, warum sich das Format als universelle Lösung eignet:

- Die Verwendung von einfachen Textdateien erlaubt die Speicherung und Verarbeitung auf unterschiedlichen Umgebungen wie Windows, Mac OS oder Linux.
- Das Format ist sehr einfach zu verstehen und daher auch für Menschen lesbar.
- Es ist ein offenes Format, d. h. es gibt keine Firma, die daran die Rechte besitzt und es kann daher von jeder Software verwendet werden. Es gab lange nicht einmal eine offizielle Spezifikation des Formats. Mittlerweile gibt es eine Spezifikation als offizieller [MIME Type](https://tools.ietf.org/html/rfc4180).


## Die Funktion `read_csv`
